### ISSUE TITLE
[0.3.0 regression] quoted attributes not compiling

### ISSUE THREAD

**Issue by heartsentwined** [machty/emblem.js#79]
This template

``` emblem
= input type='text'
input type='text'
```

compiles fine in `0.2.9`, but produces this error on `0.3.0`:

```
Pre compilation failed for: = input type='text'
input type='text'

. Compiler said: TypeError: Object #<Object> has no method 'replace'
```
