### ISSUE TITLE
Barber::PrecompilerError with handlebars 1.1.1

### ISSUE THREAD

**Issue by fwoeck** [machty/emblem.js#107]
Hi, is emblem.js currently supposed to work with handlebars 1.1.1?

I'm seeing this

```
Pre compilation failed for: = outlet

. Compiler said: TypeError: Cannot read property '3' of undefined
  (in ../assets/javascripts/templates/account.js.emblem)
```

but I'm unsure how to diagnose it further, as there's no "3" close to that context.
Maybe it's a barber issue? I opened a similar question there.
